### ISSUE TITLE
`create_embedded_template_draft.merge_fields` not working with more than one `merge_fields`

### ISSUE THREAD

**Issue by blgastesi** [withgrayce/hellosign-api#1]
## Issue

When creating a new embedded template with more than one `merge_fields` returns a `bad_request` saying that the type is missing, even if it's present. Like the following:

#### Request: 

```
HelloSign.create_embedded_template_draft({
  test_mode: 1,
  title: 'Document Title',
  file_url: ['http://www.africau.edu/images/default/sample.pdf'],
  signer_roles: [
    { name: 'Candidate' },
    { name: 'CEO' }
  ],
  merge_fields: [
    { name: "text_1", type:"text" },
    { name: "checkbox_1", type:"checkbox" }
  ]
})
```
#### Response

```
Message: {"error":{"error_msg":"Merge field is missing \"type\" parameter","error_name":"bad_request"}}
```

## Solution

Checking the code I can see that the `create_embedded_template_draft` is missing `prepare_merge_fields(opts)` 

Can we add that line? 🙏🏼

```
def create_embedded_template_draft(opts)
  opts[:client_id] ||= self.client_id
  prepare_files opts
  prepare_signer_roles opts
  prepare_attachments opts
  #### Add this line
  prepare_merge_fields opts
  HelloSign::Resource::TemplateDraft.new post("/template/create_embedded_draft", body: opts)
end
```

Cheers,

**Comment by aub** [comment]
Hi @blgastesi thanks! I agree that your solution is correct. Would you mind making a PR that includes the change and (ideally) a test to make sure that the merge fields get passed through as a JSON string? If that's a problem, I'm happy to help or walk you through it. Thanks!
